backbone: resnet50
batch_size: 2
device: cuda
dst_crs: EPSG:32636
early_stopping: false
epochs: 40
es_delta: 0.005
es_patience: 3
lr: 0.0005
metric_th: 0.8
mini_tile_size: 256
model: highresolutionnet18
src_format: jp2
threshold: 0.35
threshold_deeplab: 0.28
threshold_hrnet: 0.25
threshold_unet: 0.9
threshold_unetplusplus: 0.25
train_size: 0.85
train_val_test_dir: denmark_germany_filtered
ukr_crs: EPSG:32635
usa_crs: EPSG:32616
weigths: imagenet
